name: GraalVM Native Image builds
on:
  release:
    types: [ created ]

jobs:
  build:
    permissions: write-all
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, macos-13, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build native image
        run: mvn package -Dpackaging=native-image

      - name: Upload release
        if: github.event.release.tag_name
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            gh release upload ${{ github.event.release.tag_name }} target/asemic-cli-ubuntu
          fi
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            gh release upload ${{ github.event.release.tag_name }} target/asemic-cli-macos-arm
          fi
          if [[ "${{ matrix.os }}" == "macos-13" ]]; then
            gh release upload ${{ github.event.release.tag_name }} target/asemic-macos-x64
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
