name: GraalVM Native Image builds
on: [push, workflow_dispatch]
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-13, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
#          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build native image
        run: mvn -Pnative package

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: asemic-cli-${{ matrix.os }}
          path: target/asemic-cli
